# Generated by Django 5.1.7 on 2025-05-09 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('form', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recomendacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('categoria', models.CharField(choices=[('Governar (GV)', 'Governar (GV)'), ('Identificar (ID)', 'Identificar (ID)'), ('Proteger (PR)', 'Proteger (PR)'), ('Detectar (DE)', 'Detectar (DE)'), ('Responder (RS)', 'Responder (RS)'), ('Recuperar (RC)', 'Recuperar (RC)')], max_length=50)),
                ('tecnologia', models.CharField(default='Agnóstico', max_length=255)),
                ('nist', models.CharField(max_length=50)),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta')], max_length=50)),
                ('responsavel', models.CharField(default='Não definido', max_length=255)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('meses', models.PositiveIntegerField()),
                ('detalhes', models.TextField()),
                ('investimentos', models.CharField(max_length=255)),
                ('riscos', models.TextField(default='Não informado')),
                ('justificativa', models.TextField(default='Não informado')),
                ('observacoes', models.TextField(default='Nenhuma observação adicional')),
                ('urgencia', models.CharField(choices=[('1', 'Muito Baixo'), ('2', 'Baixo'), ('3', 'Moderado'), ('4', 'Alto'), ('5', 'Muito Alto')], max_length=1)),
                ('gravidade', models.CharField(choices=[('1', 'Muito Baixa'), ('2', 'Baixa'), ('3', 'Moderada'), ('4', 'Alta'), ('5', 'Muito Alta')], max_length=1)),
                ('cumprida', models.BooleanField(default=False)),
                ('data_cumprimento', models.DateField(blank=True, null=True)),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='comprovantes/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('perguntaId', models.TextField(default='Não informado')),
                ('analista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recomendacoes_analista', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendacoes_cliente', to=settings.AUTH_USER_MODEL)),
                ('formulario_respondido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendacoes_formulario', to='form.formulariorespondido')),
            ],
            options={
                'verbose_name': 'Recomendação',
                'verbose_name_plural': 'Recomendações',
                'ordering': ['-prioridade', 'data_fim'],
            },
        ),
    ]
