# Generated by Django 5.1.7 on 2025-04-23 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendacoes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recomendacao',
            name='responsavel',
            field=models.CharField(default='Não definido', max_length=255),
        ),
        migrations.AlterField(
            model_name='recomendacao',
            name='analista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recomendacoes_analista', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recomendacao',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendacoes_cliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recomendacao',
            name='justificativa',
            field=models.TextField(default='Não informado'),
        ),
        migrations.AlterField(
            model_name='recomendacao',
            name='observacoes',
            field=models.TextField(default='Nenhuma observação adicional'),
        ),
        migrations.AlterField(
            model_name='recomendacao',
            name='riscos',
            field=models.TextField(default='Não informado'),
        ),
        migrations.AlterField(
            model_name='recomendacao',
            name='tecnologia',
            field=models.CharField(default='Agnóstico', max_length=255),
        ),
    ]
