# Generated by Django 5.1.7 on 2025-04-23 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendacoes', '0002_recomendacao_responsavel_alter_recomendacao_analista_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recomendacao',
            name='categoria',
            field=models.CharField(choices=[('Governar (GV)', 'Governar (GV)'), ('Identificar (ID)', 'Identificar (ID)'), ('Proteger (PR)', 'Proteger (PR)'), ('Detectar (DE)', 'Detectar (DE)'), ('Responder (RS)', 'Responder (RS)'), ('Recuperar (RC)', 'Recuperar (RC)')], max_length=50),
        ),
    ]
