# Generated by Django 5.1.7 on 2025-03-31 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('GV', 'Govern'), ('ID', 'Identity'), ('PR', 'Protect'), ('DE', 'Detect'), ('RS', 'Response'), ('RC', 'Recovery')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='question',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=500),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.CreateModel(
            name='AssessmentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('politica', models.IntegerField(choices=[(1, 'Inicial'), (2, 'Repetido'), (3, 'Definido'), (4, 'Gerenciado'), (5, 'Otimizado')])),
                ('pratica', models.IntegerField(choices=[(1, 'Inicial'), (2, 'Repetido'), (3, 'Definido'), (4, 'Gerenciado'), (5, 'Otimizado')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'question')},
            },
        ),
    ]
