# Generated by Django 5.1.7 on 2025-04-24 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulariorespondido',
            name='observacoes_pendencia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formulariorespondido',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('analise', 'Em Análise'), ('pendente', 'Pendente'), ('concluido', 'Concluído')], default='rascunho', max_length=20),
        ),
    ]
