# Generated by Django 5.1.7 on 2025-04-15 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='sigla',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('sigla', models.CharField(default='SEM_SIGLA', max_length=10)),
                ('codigo', models.CharField(max_length=20)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='form.categoria')),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='form.formulario')),
            ],
            options={
                'unique_together': {('codigo', 'categoria')},
            },
        ),
        migrations.AddField(
            model_name='pergunta',
            name='subcategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='form.subcategoria'),
        ),
    ]
