# Generated by Django 5.1.7 on 2025-04-15 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_categoria_sigla_subcategoria_pergunta_subcategoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pergunta',
            name='subcategoria',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='sigla',
        ),
        migrations.DeleteModel(
            name='Subcategoria',
        ),
    ]
