# Generated by Django 5.1.7 on 2025-04-19 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maturity_assessment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maturityassessment',
            name='media_total_geral',
        ),
        migrations.RemoveField(
            model_name='maturityassessment',
            name='media_total_politica',
        ),
        migrations.RemoveField(
            model_name='maturityassessment',
            name='media_total_pratica',
        ),
    ]
